# Generated by Django 5.1.3 on 2025-01-29 18:48

import backend.models
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pre_made', 'pre-made'), ('custom', 'custom')], default='custom', max_length=10)),
                ('name', models.CharField(max_length=180)),
                ('image', models.ImageField(blank=True, upload_to=backend.models.upload_dishes_to, verbose_name='Image')),
                ('calories', models.IntegerField()),
                ('calories_100', models.IntegerField(default=0)),
                ('protein', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein_100', models.IntegerField(default=0)),
                ('carbohydrate_100', models.IntegerField(default=0)),
                ('fat_100', models.IntegerField(default=0)),
                ('drink', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=0)),
                ('portion', models.IntegerField(blank=True, default=100, null=True)),
                ('portions', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('image', models.ImageField(default='product.jpeg', upload_to=backend.models.upload_products_to, verbose_name='Image')),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
                ('fat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('tools', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('image', models.CharField(max_length=180)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('calories', models.IntegerField(null=True)),
                ('protein', models.IntegerField(null=True)),
                ('carbohydrate', models.IntegerField(null=True)),
                ('fat', models.IntegerField(null=True)),
                ('weight', models.IntegerField(default=0)),
                ('portions', models.IntegerField(default=0)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diaryDish', to='backend.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('weight', models.IntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsDish', to='backend.dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsProduct', to='backend.product')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='backend.product'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='', max_length=150)),
                ('age', models.IntegerField(default=18)),
                ('image', models.ImageField(blank=True, upload_to=backend.models.upload_to, verbose_name='Image')),
                ('calories_d', models.IntegerField(null=True)),
                ('protein_d', models.IntegerField(null=True)),
                ('carbohydrate_d', models.IntegerField(null=True)),
                ('fat_d', models.IntegerField(null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('activity_level', models.IntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, related_name='backend_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='backend_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
