# Generated by Django 5.1.3 on 2025-02-03 15:35

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_gender_user_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='cat-user.jpeg', upload_to=backend.models.upload_to, verbose_name='Image'),
        ),
    ]
