# Generated by Django 5.1.3 on 2025-02-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientsProduct', to='backend.product'),
        ),
    ]
