# Generated by Django 5.1.3 on 2025-02-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_dish_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryrecord',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaryDish', to='backend.dish'),
        ),
    ]
