# Generated by Django 5.1.3 on 2025-02-17 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_diaryrecord_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryrecord',
            name='user',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
