# Generated by Django 5.1.3 on 2025-02-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_diaryrecord_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
