# Generated by Django 5.1.3 on 2025-02-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='weight_of_ready_product',
            field=models.IntegerField(default=0),
        ),
    ]
