# Generated by Django 5.1.3 on 2025-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_dish_weight_of_ready_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
