# Generated by Django 5.1.3 on 2025-03-07 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_dish_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='favorite',
        ),
        migrations.AddField(
            model_name='dish',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_ingredients', to=settings.AUTH_USER_MODEL),
        ),
    ]
