# Generated by Django 5.1.3 on 2025-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_dish_favorite_dish_favorite_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='favorite_by',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_dishes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='backend.dish'),
        ),
    ]
