# Generated by Django 5.1.3 on 2025-03-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_dish_favorite_by_user_favorite_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
