# Generated by Django 5.1.3 on 2025-03-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='record_count',
            field=models.IntegerField(default=0),
        ),
    ]
