# Generated by Django 5.1.3 on 2025-03-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_dish_record_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='record_count',
        ),
    ]
