# Generated by Django 5.1.3 on 2025-04-22 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_dish_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('met', models.FloatField()),
                ('is_weight_based', models.BooleanField(default=False)),
                ('supports_reps', models.BooleanField(default=True)),
                ('supports_time', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('custom_workout', 'Custom Workout'), ('workout_template', 'Workout Template'), ('tabata', 'Tabata'), ('run', 'Run'), ('walk_time', 'Walk (Time)'), ('walk_steps', 'Walk (Steps)'), ('interval_run', 'Interval Run')], default='walk_time', max_length=20)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_minutes', models.FloatField(blank=True, null=True)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField()),
                ('calories_burned', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomWorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('time_minutes', models.FloatField(blank=True, null=True)),
                ('weight_group', models.CharField(choices=[('none', 'None'), ('1-5', '1–5kg'), ('5-10', '5–10kg'), ('10-15', '10–15kg'), ('15+', '15kg+')], default='none', max_length=20)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customworkout')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='customworkout',
            name='exercises',
            field=models.ManyToManyField(through='backend.CustomWorkoutExercise', to='backend.exercise'),
        ),
        migrations.CreateModel(
            name='TabataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rounds', models.PositiveIntegerField(default=8)),
                ('work_seconds', models.PositiveIntegerField(default=20)),
                ('rest_seconds', models.PositiveIntegerField(default=10)),
                ('exercises', models.ManyToManyField(to='backend.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('time_minutes', models.FloatField(blank=True, null=True)),
                ('weight_group', models.CharField(choices=[('none', 'None'), ('1-5', '1–5kg'), ('5-10', '5–10kg'), ('10-15', '10–15kg'), ('15+', '15kg+')], default='none', max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(through='backend.WorkoutExercise', to='backend.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.workouttemplate'),
        ),
    ]
