# Generated by Django 5.1.3 on 2025-04-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_exercise_activityrecord_customworkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryrecord',
            name='name',
            field=models.CharField(default='food', max_length=150),
        ),
    ]
