# Generated by Django 5.1.3 on 2025-04-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_diaryrecord_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaryRecord',
        ),
    ]
