# Generated by Django 5.1.3 on 2025-04-22 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_delete_diaryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='food', max_length=150)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('calories', models.IntegerField(null=True)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('carbohydrate', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('portions', models.IntegerField(default=0)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaryDish', to='backend.dish')),
                ('user', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
