# Generated by Django 5.1.3 on 2025-04-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_diaryrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customworkoutexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='customworkoutexercise',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='CustomWorkout',
        ),
        migrations.DeleteModel(
            name='CustomWorkoutExercise',
        ),
    ]
