# Generated by Django 5.1.3 on 2025-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_remove_customworkoutexercise_workout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
