# Generated by Django 5.1.3 on 2025-04-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_workouttemplate_total_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabatatemplate',
            name='duration',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
