# Generated by Django 5.1.3 on 2025-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_tabatatemplate_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='pace',
            field=models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='rest_time',
            field=models.IntegerField(default=30),
        ),
    ]
