# Generated by Django 5.1.3 on 2025-04-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_workoutexercise_pace_workoutexercise_rest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='rest_time',
            field=models.IntegerField(default=15),
        ),
    ]
