# Generated by Django 5.1.3 on 2025-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_workoutexercise_rest_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouttemplate',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='tabatatemplate',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='activityrecord',
            name='related_id',
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='intensity',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='activity_type',
            field=models.CharField(choices=[('workout', 'Workout'), ('tabata', 'Tabata'), ('run', 'Run'), ('walk_time', 'Walk (Time)'), ('walk_steps', 'Walk (Steps)'), ('interval_run', 'Interval Run'), ('custom', 'Custom activity'), ('volleyball', 'Volleyball')], default='walk_time', max_length=20),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='TabataTemplate',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.DeleteModel(
            name='WorkoutTemplate',
        ),
    ]
