# Generated by Django 5.1.3 on 2025-05-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_diaryrecord_caffein_diaryrecord_fiber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calculate_nutritions_from_activity_level',
            field=models.BooleanField(default=False),
        ),
    ]
