# Generated by Django 5.1.3 on 2025-05-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_user_calculate_nutritions_from_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bmr',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
