# Generated by Django 5.1.3 on 2025-05-13 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_user_bmr'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('calories_burned_goal', models.PositiveIntegerField(default=0)),
                ('protein', models.PositiveIntegerField(default=0)),
                ('protein_goal', models.PositiveIntegerField(default=0)),
                ('carbohydrate', models.PositiveIntegerField(default=0)),
                ('carbohydrate_goal', models.PositiveIntegerField(default=0)),
                ('fat', models.PositiveIntegerField(default=0)),
                ('fat_goal', models.PositiveIntegerField(default=0)),
                ('fiber', models.PositiveIntegerField(default=0)),
                ('fiber_goal', models.PositiveIntegerField(default=0)),
                ('sugars', models.PositiveIntegerField(default=0)),
                ('sugars_goal', models.PositiveIntegerField(default=0)),
                ('caffein', models.PositiveIntegerField(default=0)),
                ('caffein_goal', models.PositiveIntegerField(default=0)),
                ('calories_intake', models.PositiveIntegerField(default=0)),
                ('calories_intake_goal', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
