# Generated by Django 5.1.3 on 2025-05-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_dailygoals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailygoals',
            old_name='caffein',
            new_name='caffeine',
        ),
        migrations.RenameField(
            model_name='dailygoals',
            old_name='caffein_goal',
            new_name='caffeine_goal',
        ),
    ]
