# Generated by Django 5.1.3 on 2025-05-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_alter_activityrecord_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailygoals',
            unique_together={('user', 'date')},
        ),
    ]
