# Generated by Django 5.1.3 on 2025-05-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_alter_dailygoals_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoals',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
