# Generated by Django 5.1.3 on 2025-05-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_alter_dailygoals_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='activity_type',
            field=models.CharField(choices=[('workout', 'Workout'), ('tabata', 'Tabata'), ('run', 'Run'), ('walk_time', 'Walk (Time)'), ('walk_steps', 'Walk (Steps)'), ('interval_run', 'Interval Run'), ('custom', 'Custom activity'), ('volleyball', 'Volleyball'), ('stretching', 'Stretching'), ('jumping', 'Jumping'), ('home_chores', 'Home chores')], default='walk_time', max_length=20),
        ),
    ]
