# Generated by Django 5.1.3 on 2025-06-04 08:44

import backend.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_product_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUUID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('image', models.ImageField(default='product.jpeg', upload_to=backend.models.upload_products_to, verbose_name='Image')),
                ('calories', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=1, max_digits=10)),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fiber', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('sugars', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('caffeine', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='productUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
