# Generated by Django 5.1.3 on 2025-06-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_productuuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductUUID',
        ),
    ]
