# Generated by Django 5.1.3 on 2025-06-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_rename_product_productold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductUUID',
            new_name='Product',
        ),
    ]
