# Generated by Django 5.1.3 on 2025-06-04 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_rename_productuuid_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='product_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.product'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.product'),
        ),
    ]
