# Generated by Django 5.1.3 on 2025-06-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_dish_product_uuid_ingredient_product_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='product',
            new_name='product_old',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='product',
            new_name='product_old',
        ),
    ]
