# Generated by Django 5.1.3 on 2025-06-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_rename_product_dish_product_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='product_uuid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='product_uuid',
            new_name='product',
        ),
    ]
