# Generated by Django 5.1.3 on 2025-06-05 14:15

import backend.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_product_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishUUID',
            fields=[
                ('id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pre_made', 'pre-made'), ('custom', 'custom')], default='custom', max_length=10)),
                ('name', models.CharField(max_length=180)),
                ('image', models.ImageField(blank=True, upload_to=backend.models.upload_dishes_to, verbose_name='Image')),
                ('calories', models.IntegerField()),
                ('calories_100', models.IntegerField(default=0)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=10)),
                ('carbohydrate', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('fiber', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('sugars', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('caffein', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('protein_100', models.DecimalField(decimal_places=1, max_digits=10)),
                ('carbohydrate_100', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fat_100', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fiber_100', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('sugars_100', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('caffein_100', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('drink', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=0)),
                ('portion', models.IntegerField(blank=True, default=100, null=True)),
                ('portions', models.IntegerField(blank=True, default=1, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('weight_of_ready_product', models.IntegerField(blank=True, default=0, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.product')),
                ('product_old', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.productold')),
                ('user', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dish_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsDishUUID', to='backend.dishuuid'),
        ),
    ]
