# Generated by Django 5.1.3 on 2025-06-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_dishuuid_ingredient_dish_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryrecord',
            name='dish_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaryDishUUID', to='backend.dishuuid'),
        ),
        migrations.AddField(
            model_name='dishuuid',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dishuuid',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
