# Generated by Django 5.1.3 on 2025-06-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_diaryrecord_dish_uuid_dishuuid_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='DishOld',
        ),
    ]
