# Generated by Django 5.1.3 on 2025-06-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_rename_dish_dishold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DishUUID',
            new_name='Dish',
        ),
    ]

