# Generated by Django 5.1.3 on 2025-06-05 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_auto_20250605_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryrecord',
            old_name='dish',
            new_name='dish_old',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='dish',
            new_name='dish_old',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_dishes',
        ),
        migrations.AlterField(
            model_name='dish',
            name='product_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_product', to='backend.productold'),
        ),
    ]
