# Generated by Django 5.1.3 on 2025-06-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_rename_dish_diaryrecord_dish_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryrecord',
            old_name='dish_uuid',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='dish_uuid',
            new_name='dish',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_dishes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='backend.dish'),
        ),
    ]
