# Generated by Django 5.1.3 on 2025-06-05 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_rename_dish_uuid_diaryrecord_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsDish', to='backend.dish'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='dish_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsDishOld', to='backend.dishold'),
        ),
    ]
