# Generated by Django 5.1.3 on 2025-06-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_alter_ingredient_dish_alter_ingredient_dish_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='carbohydrate',
            new_name='carbs',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='carbohydrate_100',
            new_name='carbs_100',
        ),
    ]
