# Generated by Django 5.1.3 on 2025-06-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_rename_carbohydrate_dish_carbs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='caffein',
            new_name='caffeine',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='caffein',
            new_name='caffeine',
        ),
    ]
