# Generated by Django 5.1.3 on 2025-06-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_rename_caffein_dish_caffeine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryrecord',
            old_name='caffein',
            new_name='caffeine',
        ),
        migrations.RenameField(
            model_name='diaryrecord',
            old_name='carbohydrate',
            new_name='carbs',
        ),
    ]
