# Generated by Django 5.1.3 on 2025-06-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_rename_caffein_diaryrecord_caffeine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='caffein_100',
            new_name='caffeine_100',
        ),
    ]
