# Generated by Django 5.1.3 on 2025-06-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_rename_caffein_100_dish_caffeine_100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
