# Generated by Django 5.1.3 on 2025-06-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_alter_dish_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='IngredientOld',
        ),
    ]
