# Generated by Django 5.1.3 on 2025-06-09 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_rename_ingredient_ingredientold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientold',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsOldDish', to='backend.dish'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calories', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=1, max_digits=10)),
                ('carbohydrate', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('fiber', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('sugars', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('caffeine', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('weight', models.IntegerField(default=0)),
                ('name', models.CharField(default='')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsDish', to='backend.dish')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.product')),
            ],
        ),
    ]
