# Generated by Django 5.1.3 on 2025-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_alter_ingredientold_dish_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
