# Generated by Django 5.1.3 on 2025-06-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_ingredient_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
