# Generated by Django 5.1.3 on 2025-06-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_ingredient_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='carbohydrate',
            new_name='carbs',
        ),
    ]
