# Generated by Django 5.1.3 on 2025-06-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_rename_carbohydrate_ingredient_carbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.UUIDField(default=None, primary_key=True, serialize=False),
        ),
    ]
