# Generated by Django 5.1.3 on 2025-06-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_alter_ingredient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
    ]
