# Generated by Django 5.1.3 on 2025-06-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_diaryrecorduuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiaryRecord',
            new_name='DiaryRecordOLD',
        ),
    ]
