# Generated by Django 5.1.3 on 2025-06-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_rename_diaryrecord_diaryrecordold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiaryRecordUUID',
            new_name='DiaryRecord',
        ),
    ]
