# Generated by Django 5.1.3 on 2025-06-12 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_rename_diaryrecorduuid_diaryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecordUUID',
            fields=[
                ('id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('workout', 'Workout'), ('tabata', 'Tabata'), ('run', 'Run'), ('walk_time', 'Walk (Time)'), ('walk_steps', 'Walk (Steps)'), ('interval_run', 'Interval Run'), ('custom', 'Custom activity'), ('volleyball', 'Volleyball'), ('stretching', 'Stretching'), ('jumping', 'Jumping'), ('home_chores', 'Home chores')], default='walk_time', max_length=20)),
                ('duration_minutes', models.FloatField(blank=True, null=True)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField()),
                ('intensity', models.PositiveIntegerField(default=3)),
                ('calories_burned', models.FloatField()),
                ('timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyGoalsUUID',
            fields=[
                ('id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('calories_burned_goal', models.PositiveIntegerField(default=0)),
                ('protein', models.PositiveIntegerField(default=0)),
                ('protein_goal', models.PositiveIntegerField(default=0)),
                ('carbohydrate', models.PositiveIntegerField(default=0)),
                ('carbohydrate_goal', models.PositiveIntegerField(default=0)),
                ('fat', models.PositiveIntegerField(default=0)),
                ('fat_goal', models.PositiveIntegerField(default=0)),
                ('fiber', models.PositiveIntegerField(default=0)),
                ('fiber_goal', models.PositiveIntegerField(default=0)),
                ('sugars', models.PositiveIntegerField(default=0)),
                ('sugars_goal', models.PositiveIntegerField(default=0)),
                ('caffeine', models.PositiveIntegerField(default=0)),
                ('caffeine_goal', models.PositiveIntegerField(default=0)),
                ('calories_intake', models.PositiveIntegerField(default=0)),
                ('calories_intake_goal', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
