# Generated by Django 5.1.3 on 2025-06-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_rename_activityrecord_activityrecordold_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityRecordUUID',
            new_name='ActivityRecord',
        ),
        migrations.RenameModel(
            old_name='DailyGoalsUUID',
            new_name='DailyGoals',
        ),
    ]
