# Generated by Django 5.1.3 on 2025-06-13 07:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_rename_activityrecorduuid_activityrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoals',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb657ae4-669e-45e4-b51e-d31fe3e18a81'), primary_key=True, serialize=False),
        ),
    ]
