# Generated by Django 5.1.3 on 2025-06-17 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_alter_dailygoals_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailygoals',
            old_name='carbohydrate',
            new_name='carbs',
        ),
        migrations.RenameField(
            model_name='dailygoals',
            old_name='carbohydrate_goal',
            new_name='carbs_goal',
        ),
        migrations.AlterField(
            model_name='dailygoals',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f22363a8-1e81-4a20-9d46-92c057341b38'), primary_key=True, serialize=False),
        ),
    ]
