# Generated by Django 5.1.3 on 2025-06-17 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_rename_caffein_d_user_caffeine_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailygoals',
            name='id',
            field=models.UUIDField(default=uuid.UUID('872eb939-2f03-42fb-a46c-d691ad2cf974'), primary_key=True, serialize=False),
        ),
    ]
