# Generated by Django 5.1.3 on 2025-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_activityrecord_is_deleted_alter_dailygoals_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoals',
            name='id',
            field=models.UUIDField(default=None, primary_key=True, serialize=False),
        ),
    ]
