# Generated by Django 5.1.3 on 2025-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_alter_dailygoals_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
