# Generated by Django 5.1.3 on 2025-06-19 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_activityrecord_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoals',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76ea9325-9308-465c-ae6d-53c5ef593fad'), primary_key=True, serialize=False),
        ),
    ]
