# Generated by Django 5.1.3 on 2025-06-27 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0089_alter_dailygoals_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoals',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
