EXERCISES_MET = [
    {"name": "Jumping Jacks", "met": 8.0},
    {"name": "Push-ups", "met": 8.0},
    {"name": "Squats", "met": 5.0},
    {"name": "Lunges", "met": 5.0},
    {"name": "Plank", "met": 3.3},
    {"name": "Burpees", "met": 10.0},
    {"name": "High Knees", "met": 8.0},
    {"name": "Mountain Climbers", "met": 8.0},
    {"name": "Jump Rope", "met": 12.3},
    {"name": "Pull-ups", "met": 8.0},
    {"name": "Dumbbell Curls (light)", "met": 3.5},
    {"name": "Dumbbell Curls (heavy)", "met": 6.0},
    {"name": "Bench Press", "met": 6.0},
    {"name": "Deadlift", "met": 6.0},
    {"name": "Cycling (moderate)", "met": 7.5},
    {"name": "Running (6 mph)", "met": 9.8},
    {"name": "Walking (3 mph)", "met": 3.5},
    {"name": "Stretching", "met": 2.3},
    {"name": "Yoga (Vinyasa)", "met": 5.5},
    {"name": "Pilates", "met": 3.0},
]
